version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    links:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379

  web:
    build: .
    command: gunicorn Settings.asgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - DEBUG=0
    ports:
      - 8000:8000
    depends_on:
      - db

