# Generated by Django 4.1.3 on 2022-11-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Something', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ZhuGhoul', max_length=20, verbose_name='CAR NAME')),
                ('lvl', models.PositiveSmallIntegerField(default=1, verbose_name='LVL')),
                ('engine', models.FloatField(verbose_name='ENGINE')),
                ('first', models.PositiveIntegerField(verbose_name='GEAR_1')),
                ('second', models.PositiveIntegerField(verbose_name='GEAR_2')),
                ('third', models.PositiveIntegerField(verbose_name='GEAR_3')),
                ('fouth', models.PositiveIntegerField(verbose_name='GEAR_4')),
                ('fivth', models.PositiveIntegerField(verbose_name='GEAR_5')),
                ('max_speed', models.PositiveIntegerField(verbose_name='MAX')),
                ('wheels', models.FloatField(verbose_name='WHEELS')),
                ('turbo', models.BooleanField(verbose_name='TURBO')),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='ghoul_power',
        ),
        migrations.AddField(
            model_name='newuser',
            name='active',
            field=models.BooleanField(default=False, verbose_name='ACTIVE_EMAIL'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='ghoul_lvl',
            field=models.PositiveIntegerField(default=1, verbose_name='POWER'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='balance',
            field=models.PositiveIntegerField(default=100, verbose_name='BALANCE'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='img',
            field=models.ImageField(default='users/zxc.jpg', upload_to='users/', verbose_name='IMG'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='name',
            field=models.CharField(default='NONAME', max_length=50, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='username',
            field=models.CharField(default='NoName', max_length=50, unique=True, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.PositiveSmallIntegerField(verbose_name='LVL')),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Something.car', verbose_name='MYCAR')),
            ],
        ),
        migrations.AddField(
            model_name='newuser',
            name='car',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Something.car', verbose_name='MYCAR'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='enemy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Something.enemy', verbose_name='ENEMY'),
        ),
    ]
