# Generated by Django 4.1.3 on 2022-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Something', '0002_car_remove_newuser_ghoul_power_newuser_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ENGINE'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheels',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='WHEELS'),
        ),
    ]
