# Generated by Django 4.1.3 on 2022-11-30 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Something', '0003_alter_car_engine_alter_car_wheels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ROOM')),
                ('num', models.PositiveSmallIntegerField(default=1, verbose_name='Count')),
                ('player_1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person1', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('player_2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person2', to=settings.AUTH_USER_MODEL, verbose_name='user2')),
            ],
        ),
    ]
